#### 1. What is the numpy version

> version 1.23.3

In [1]:
import numpy as np

np.__version__

'1.23.3'

In [2]:
import wget

In [3]:
url= "https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv"
data = wget.download(url)


100% [......................................................] 1475504 / 1475504

#### 2. Number of records

> 11914

In [4]:
import pandas as pd
df = pd.read_csv(data)
df.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [5]:
len(df.index)

11914

In [6]:
df.shape[0]

11914

In [7]:
df[df.columns[0]].count()

11914

#### 3. Top 3 manufacturers
> Chevrolet, Ford, VW

In [8]:
df["Make"].value_counts()

Chevrolet        1123
Ford              881
Volkswagen        809
Toyota            746
Dodge             626
Nissan            558
GMC               515
Honda             449
Mazda             423
Cadillac          397
Mercedes-Benz     353
Suzuki            351
BMW               334
Infiniti          330
Audi              328
Hyundai           303
Volvo             281
Subaru            256
Acura             252
Kia               231
Mitsubishi        213
Lexus             202
Buick             196
Chrysler          187
Pontiac           186
Lincoln           164
Oldsmobile        150
Land Rover        143
Porsche           136
Saab              111
Aston Martin       93
Plymouth           82
Bentley            74
Ferrari            69
FIAT               62
Scion              60
Maserati           58
Lamborghini        52
Rolls-Royce        31
Lotus              29
Tesla              18
HUMMER             17
Maybach            16
Alfa Romeo          5
McLaren             5
Spyker    

#### 4. Uniqe Audi car models
> 16

In [9]:
aud = df[df['Make'] == 'Audi']
aud.head()
aud.nunique().count()

16

#### 5. Columns with missing dataset
> 5

In [10]:
df.isnull().sum()

Make                    0
Model                   0
Year                    0
Engine Fuel Type        3
Engine HP              69
Engine Cylinders       30
Transmission Type       0
Driven_Wheels           0
Number of Doors         6
Market Category      3742
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
dtype: int64

In [11]:
(df.isnull().sum() != 0).sum()

5

#### 6. Engine Cylinders
> * median = 6.0
> * most frequent = 4.0

In [12]:
df["Engine Cylinders"].median()

6.0

In [13]:
# Most frequest value (mode)
df["Engine Cylinders"].value_counts()

4.0     4752
6.0     4489
8.0     2031
12.0     230
5.0      225
10.0      68
0.0       56
3.0       30
16.0       3
Name: Engine Cylinders, dtype: int64

In [14]:
# mode
mode = df["Engine Cylinders"].mode()[0]
mode

4.0

In [15]:
df["Engine Cylinders"].fillna(mode)


0        6.0
1        6.0
2        6.0
3        6.0
4        6.0
        ... 
11909    6.0
11910    6.0
11911    6.0
11912    6.0
11913    6.0
Name: Engine Cylinders, Length: 11914, dtype: float64

In [16]:
df["Engine Cylinders"].median()

6.0

#### 7. Lotus

In [17]:
lotus = df[df["Make"] == 'Lotus']
lotus = lotus[["Engine HP","Engine Cylinders"]]
lotus.head()

Engine HP  Engine Cylinders
3912      189.0               4.0
3913      218.0               4.0
3914      189.0               4.0
3915      189.0               4.0
3916      218.0               4.0

In [18]:
lotus.shape[0]

29

In [19]:
lotus.duplicated().count()

29

In [22]:
lotus = lotus.drop_duplicates()

In [23]:
lotus.shape[0]

9

In [24]:
X = np.array(lotus)
X

array([[189.,   4.],
       [218.,   4.],
       [217.,   4.],
       [350.,   8.],
       [400.,   6.],
       [276.,   6.],
       [345.,   6.],
       [257.,   4.],
       [240.,   4.]])

In [26]:
XTX = X.T @ X
XTX

array([[7.31684e+05, 1.34100e+04],
       [1.34100e+04, 2.52000e+02]])

In [28]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 5.53084235e-05, -2.94319825e-03],
       [-2.94319825e-03,  1.60588447e-01]])

In [29]:
y = np.array([1100, 800, 750, 850, 1300, 1000, 1000, 1300, 800])
y

array([1100,  800,  750,  850, 1300, 1000, 1000, 1300,  800])

In [30]:
w = (XTX_inv @ X.T) @ y
w

array([  4.59494481, -63.56432501])

In [31]:
w[0]

4.594944810094551