### One Dimensional Array

In [2]:
import numpy as np

In [3]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [4]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [5]:
np.full(10, 2.5) # array of size 10 with 2.5

array([2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5, 2.5])

In [6]:
# creating an array from a list
np.array([1,2,4,7,10])

array([ 1,  2,  4,  7, 10])

In [7]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(3,9)

array([3, 4, 5, 6, 7, 8])

In [15]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

### Multi-dimentional arrays

In [16]:
# Array of 5 rows and two columns (zeros)
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

### Randomly generated arrays

In [23]:
# Random generation of 
np.random.seed(2) #the seed ensures a stand uniform distribution
np.random.rand(5,2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [24]:
np.random.seed(2) #the seed ensures a stand uniform distribution
np.random.randn(5,2) # n at the end ensures a random normal distribution

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [26]:
np.random.seed(2) #the seed ensures a stand uniform distribution
np.random.randint(size=(5,2), low=0, high=100) #randint generates a random integer

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

### Element-wise operators

In [28]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [29]:
a + 5

array([5, 6, 7, 8, 9])

### Operations

In [31]:
a.min()

0

In [32]:
a.max()

4

In [33]:
a.mean()

2.0

In [35]:
a.std()

1.4142135623730951

In [36]:
a.sum()

10