In [3]:
import numpy as np

In [4]:
u = np.array([2,7,5,6])
v = np.array([3,4,8,6])

# addition
u + v

array([ 5, 11, 13, 12])

In [5]:
# substraction
u - v 

array([-1,  3, -3,  0])

In [6]:
# scalar multiplication
2 * v

array([ 6,  8, 16, 12])

## Multiplication

### vector-vector multiplication

In [7]:
print(f'shape of u is:{u.shape}')
print(f'shape of v is:{v.shape}')

shape of u is:(4,)
shape of v is:(4,)


In [8]:
def vec_mult(u,v):
    assert u.shape[0] == v.shape[0] #making sure the vectors are of the same size
    
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]
    return result

In [9]:
vec_mult(u,v)

110.0

In [10]:
# alternative approach
u.dot(v)

110

### Matrix-vector multiplication

In [11]:
x = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1]
])

x.shape

(3, 4)

In [12]:
print(f'no. of rows: {x.shape[0]}') # [0] is for rows
print(f'no. of columns: {x.shape[1]}') # [1] is for columns

no. of rows: 3
no. of columns: 4


In [13]:
def matrix_vector_mul(x,v):
    assert x.shape[1] == v.shape[0]
    num_rows = x.shape[0]
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vec_mult(x[i],v)
    return result

In [14]:
matrix_vector_mul(x,v)

array([98., 31., 35.])

In [15]:
x.dot(v)

array([98, 31, 35])

### Matrix-matrix multiplication

In [16]:
y = np.array([[1,1,2],
              [0,0.5,1],
              [0,2,1],
              [2,1,0]
             ])

In [17]:
def matrix_matrix_mul(x,y):
    assert x.shape[1] == y.shape[0]
    
    num_rows = x.shape[0]
    num_cols = y.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        yi = y[:,i]
        uyi = matrix_vector_mul(x,yi)
        result[:,i] = uyi
        
    return result

In [18]:
matrix_matrix_mul(x,y)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [19]:
x.dot(y)

array([[14. , 20. , 13. ],
       [ 5. ,  6. ,  5. ],
       [ 5. ,  8.5,  9. ]])

In [20]:
# Identity matrix
I = np.eye(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
# Inverse
inv = np.linalg.inv(x.dot(y))
inv

array([[-0.1503268 ,  0.90849673, -0.2875817 ],
       [ 0.26143791, -0.79738562,  0.06535948],
       [-0.16339869,  0.24836601,  0.20915033]])